// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePassfile(arg1) {
  return window['go']['app']['app']['CreatePassfile'](arg1);
}

export function DeletePassfile() {
  return window['go']['app']['app']['DeletePassfile']();
}

export function GeneratePassword(arg1, arg2, arg3, arg4) {
  return window['go']['app']['app']['GeneratePassword'](arg1, arg2, arg3, arg4);
}

export function ImportPassfile() {
  return window['go']['app']['app']['ImportPassfile']();
}

export function ListPasswords() {
  return window['go']['app']['app']['ListPasswords']();
}

export function OpenPassfile(arg1) {
  return window['go']['app']['app']['OpenPassfile'](arg1);
}

export function PassfileExists() {
  return window['go']['app']['app']['PassfileExists']();
}

export function PassfileOpened() {
  return window['go']['app']['app']['PassfileOpened']();
}

export function SavePassword(arg1, arg2) {
  return window['go']['app']['app']['SavePassword'](arg1, arg2);
}

export function ShowPassword(arg1) {
  return window['go']['app']['app']['ShowPassword'](arg1);
}

export function Version() {
  return window['go']['app']['app']['Version']();
}
